{\rtf1\ansi\ansicpg1252\cocoartf2865
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww29200\viewh15720\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 name: Deploy to EC2\
\
on:\
  push:\
    branches:\
      - main\
\
jobs:\
  build-and-deploy:\
    runs-on: ubuntu-latest\
\
    steps:\
      - name: Checkout code\
        uses: actions/checkout@v3\
\
      - name: Set up Java\
        uses: actions/setup-java@v3\
        with:\
          java-version: '17'\
          distribution: 'temurin'\
\
      - name: Build with Maven\
        run: mvn clean package -DskipTests\
\
      - name: Copy JAR to EC2\
        uses: appleboy/scp-action@v0.1.7\
        with:\
          host: $\{\{ secrets.EC2_HOST \}\}\
          username: $\{\{ secrets.EC2_USER \}\}\
          key: $\{\{ secrets.EC2_SSH_KEY \}\}\
          source: "target/*.jar"\
          target: "/home/ec2-user/app"\
\
      - name: Restart App on EC2\
        uses: appleboy/ssh-action@v0.1.10\
        with:\
          host: $\{\{ secrets.EC2_HOST \}\}\
          username: $\{\{ secrets.EC2_USER \}\}\
          key: $\{\{ secrets.EC2_SSH_KEY \}\}\
          script: |\
            pkill -f 'java -jar' || true\
            nohup java -jar /home/ec2-user/app/interactiveapp-0.0.1-SNAPSHOT.jar > app.log 2>&1 &\
            echo "App restarted successfully!"\
}